export { SetCoreCommands } from './SetCoreCommands'
export { SetHeadings } from './SetHeadings'
export { SetColor } from './SetColor'
export { SetCustomLink } from './setCustomLink'
export { SetFontSize } from './SetFontSize'
