image: node:10-alpine

stages:
  - install
  - test
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - apk add --no-cache git
    - yarn
  artifacts:
    paths:
      - node_modules/

testing:
  stage: test
  script:
    - npm test

building:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - build/
