image: node:lts-alpine

variables:
  PORT: 3047

stages:
  - lint
  - build
  - deploy

lint:
  stage: lint
  script:
    - npm i
    - npm run lint
    - npm run build
  only:
    - merge_requests

publish:
  stage: build
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
    NPM_TOKEN: $NPM_TOKEN
  before_script:
    - apk update && apk upgrade && apk add --no-cache bash git
  script:
    - npm i
    - npm config set @ecom:registry $NPM_REGISTRY/npm-internal/
    - npm run publish-ui
  only:
    - master

deploy to test:
  stage: deploy
  tags:
    - urt-web-app1-for-web-gr
  variables:
    HOST: $TEST_HOST
    NODE_ENV: production
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker-compose down
    - docker-compose build --build-arg HTTPS_PROXY=$PROXY ui
    - docker-compose up -d
    - docker stats --no-stream
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - test
