image: node:lts-alpine

variables:
  PORT: 3040

stages:
  - lint
  - build
  - deploy

lint:
  stage: lint
  script:
    - npm i
    - npm run build
  only:
    - merge_requests

deploy to test:
  stage: deploy
  tags:
    - urt-web-app1-for-web-gr
  variables:
    HOST: $TEST_HOST
    NODE_ENV: test
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker-compose down
    - docker-compose build --build-arg HTTPS_PROXY=$PROXY ui
    - docker-compose up -d
    - docker system prune -af
    - docker stats --no-stream
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - test

building:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - build/
  only:
    - master
