image: registry.sovcombank.group/project-cache/library/node:18

variables:
  PORT: 3047

stages:
  - test
  - build
  - deploy

lint:
  stage: test
  before_script:
    - export http_proxy=${PROXY}
    - export https_proxy=${PROXY}
    - export no_proxy=${NO_PROXY}
    - npm config set registry $NPM_REGISTRY/npm-all/
  script:
    - npm ci
    - npm run lint
    - npm run ts-check
    - npm run build
  only:
    - merge_requests

unit:
  stage: test
  before_script:
    - export http_proxy=${PROXY}
    - export https_proxy=${PROXY}
    - export no_proxy=${NO_PROXY}
    - sh docker.sh
    - docker -v
    - apt install net-tools -y
  only:
    - beta
    - merge_requests
  script:
    - npm i
    - npm run test

sb:
  stage: test
  before_script:
    - export http_proxy=${PROXY}
    - export https_proxy=${PROXY}
    - export no_proxy=${NO_PROXY}
    - sh docker.sh
    - docker -v
    - apt install net-tools -y
  only:
    - beta
    - merge_requests
  script:
    - npm i
    - npx playwright install --with-deps
    - npm run test:sb

publish:
  stage: build
  variables:
    GITLAB_TOKEN: $GITLAB_UI_TOKEN
    NPM_TOKEN: $NPM_TOKEN
    GRAYLOG_URL: udp://$GRAYLOG
    HUSKY: 0 # To disable hooks installation
  before_script:
    - export http_proxy=${PROXY}
    - export https_proxy=${PROXY}
    - export no_proxy=${NO_PROXY}
    - apk update && apk upgrade && apk add --no-cache bash git
  script:
    - npm i
    - npm config set @ecom:registry $NPM_REGISTRY/npm-internal/
    - npm run publish:ui
  only:
    - master
    - beta

deploy to test:
  stage: deploy
  tags:
    - urt-web-app1-for-web-gr
  variables:
    HOST: $TEST_HOST
    NODE_ENV: production
    GRAYLOG_URL: udp://$TEST_GRAYLOG
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker-compose down
    - docker-compose build --build-arg HTTPS_PROXY=$PROXY ui
    - docker-compose up -d
    - docker stats --no-stream
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - test
    - beta
