image: registry.sovcombank.group/project-cache/library/node:18

variables:
  PORT: 3047

stages:
  - lint
  - test
  - build
  - deploy

lint:
  stage: lint
  before_script:
    - npm config set registry $NPM_REGISTRY/npm-all/
  script:
    - npm ci
    - npm run lint
    - npm run build
  only:
    - merge_requests

test:
  image: registry.sovcombank.group/library/library/docker:git
  stage: test
  only:
    - beta
  when: manual
  allow_failure: true
  script:
    - npm i
    - npm run test-ci

publish:
  stage: build
  variables:
    GITLAB_TOKEN: $GITLAB_UI_TOKEN
    NPM_TOKEN: $NPM_TOKEN
    GRAYLOG_URL: udp://$GRAYLOG
  before_script:
    - export http_proxy=${PROXY}
    - export https_proxy=${PROXY}
    - export no_proxy=${NO_PROXY}
    - apk update && apk upgrade && apk add --no-cache bash git
  script:
    - npm i
    - npm config set @ecom:registry $NPM_REGISTRY/npm-internal/
    - npm run publish-ui
  only:
    - master
    - beta

deploy to test:
  stage: deploy
  tags:
    - urt-web-app1-for-web-gr
  variables:
    HOST: $TEST_HOST
    NODE_ENV: production
    GRAYLOG_URL: udp://$TEST_GRAYLOG
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker-compose down
    - docker-compose build --build-arg HTTPS_PROXY=$PROXY ui
    - docker-compose up -d
    - docker stats --no-stream
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - test
    - beta
