
version: '2'
services:
  ui:
    build: .
    environment:
      - HOST
      - NODE_ENV
    ports:
      - $PORT:8080
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: $HOST:24224
        tag: docker.ui
    network_mode: bridge
