version: "2"
services:
  ui:
    container_name: ui
    build:
      context: .
      args:
        - NPM_REGISTRY
        - PROXY
        - NO_PROXY
    environment:
      - NODE_ENV
    ports:
      - $PORT:80
    mem_limit: 1g
    network_mode: bridge
