export { PageHeader, type TPageHeaderProps } from './pageHeader'
export { Banner, type IBannerProps } from './banner'
export { Advantages, type IAdvantage, type IAdvantagesProps } from './Advantages'
export { Footer, type IFooterProps } from './footer'
export { Stepper, type IStepperProps, type ISingleStep } from './stepper'
