import type { AllowedIcons } from '$/shared/ui/icon'

export const allowedIcons: {
  group: Record<string, AllowedIcons[]>
  flatten: AllowedIcons[]
} = {
  group: {
    arrows: ['arrows/arrowCircle', 'arrows/arrowLink', 'arrows/arrowRight', 'arrows/arrowRotate', 'arrows/arrowScroll'],
    brandLogos: [
      'brandLogos/logoBlack',
      'brandLogos/logoBusiness',
      'brandLogos/logoGray',
      'brandLogos/logoInsurance',
      'brandLogos/logoMain',
      'brandLogos/logoWhite'
    ],
    editor: [
      'editor/bold',
      'editor/heading',
      'editor/italic',
      'editor/link',
      'editor/list',
      'editor/palette',
      'editor/redo',
      'editor/removeFormatting',
      'editor/space',
      'editor/strikethrough',
      'editor/typography',
      'editor/underline',
      'editor/undo'
    ],
    files: ['files/border', 'files/borderError', 'files/documentFilled', 'files/documentOutline', 'files/upload'],
    general: [
      'general/calendar',
      'general/check',
      'general/close',
      'general/edit',
      'general/hiddenEye',
      'general/plus',
      'general/reorder',
      'general/showEye'
    ],
    info: ['info/helpCircle', 'info/warningCircle'],
    logos: ['logos/beeline', 'logos/megafon', 'logos/mts'],
    social: ['social/classmates', 'social/telegram', 'social/vk'],
    status: ['status/badSmile', 'status/iconMark', 'status/iconRetry', 'status/iconUser']
  },
  flatten: [
    'arrows/arrowCircle',
    'arrows/arrowLink',
    'arrows/arrowRight',
    'arrows/arrowRotate',
    'arrows/arrowScroll',
    'brandLogos/logoBlack',
    'brandLogos/logoBusiness',
    'brandLogos/logoGray',
    'brandLogos/logoInsurance',
    'brandLogos/logoMain',
    'brandLogos/logoWhite',
    'editor/bold',
    'editor/heading',
    'editor/italic',
    'editor/link',
    'editor/list',
    'editor/palette',
    'editor/redo',
    'editor/removeFormatting',
    'editor/space',
    'editor/strikethrough',
    'editor/typography',
    'editor/underline',
    'editor/undo',
    'files/border',
    'files/borderError',
    'files/documentFilled',
    'files/documentOutline',
    'files/upload',
    'general/calendar',
    'general/check',
    'general/close',
    'general/edit',
    'general/hiddenEye',
    'general/plus',
    'general/reorder',
    'general/showEye',
    'info/helpCircle',
    'info/warningCircle',
    'logos/beeline',
    'logos/megafon',
    'logos/mts',
    'social/classmates',
    'social/telegram',
    'social/vk',
    'status/badSmile',
    'status/iconMark',
    'status/iconRetry',
    'status/iconUser'
  ]
}
