export type AllowedIcons = (typeof allowedIcons.flatten)[number]

export type AllowedIconsGroup<T extends keyof typeof allowedIcons.group> = (typeof allowedIcons.group)[T][number]

export const allowedIcons = {
  group: {
    status: ['status/badSmile', 'status/iconMark', 'status/iconRetry', 'status/iconUser', 'status/succesCircle'],
    social: ['social/classmates', 'social/telegram', 'social/vk'],
    media: ['media/desktop', 'media/mobile'],
    logos: ['logos/beeline', 'logos/megafon', 'logos/mts'],
    info: ['info/helpCircle', 'info/warningCircle'],
    general: [
      'general/calendar',
      'general/check',
      'general/close',
      'general/edit',
      'general/heart',
      'general/hiddenEye',
      'general/loginFilled',
      'general/menu',
      'general/optionsHorizontal',
      'general/optionsVertical',
      'general/plus',
      'general/reorder',
      'general/search',
      'general/shield',
      'general/showEye'
    ],
    files: [
      'files/border',
      'files/borderError',
      'files/documentFilled',
      'files/documentOutline',
      'files/fileMultiple',
      'files/upload'
    ],
    editor: [
      'editor/bold',
      'editor/fonts',
      'editor/heading',
      'editor/italic',
      'editor/link',
      'editor/list',
      'editor/palette',
      'editor/redo',
      'editor/removeFormatting',
      'editor/space',
      'editor/strikethrough',
      'editor/typography',
      'editor/underline',
      'editor/undo'
    ],
    communication: ['communication/phone'],
    brandLogos: [
      'brandLogos/logoBlack',
      'brandLogos/logoBusiness',
      'brandLogos/logoGray',
      'brandLogos/logoInsurance',
      'brandLogos/logoMain',
      'brandLogos/logoWhite'
    ],
    arrows: [
      'arrows/arrowCircle',
      'arrows/arrowDownRight',
      'arrows/arrowLink',
      'arrows/arrowRight',
      'arrows/arrowRotate',
      'arrows/arrowScroll'
    ]
  },
  flatten: [
    'status/badSmile',
    'status/iconMark',
    'status/iconRetry',
    'status/iconUser',
    'status/succesCircle',
    'social/classmates',
    'social/telegram',
    'social/vk',
    'media/desktop',
    'media/mobile',
    'logos/beeline',
    'logos/megafon',
    'logos/mts',
    'info/helpCircle',
    'info/warningCircle',
    'general/calendar',
    'general/check',
    'general/close',
    'general/edit',
    'general/heart',
    'general/hiddenEye',
    'general/loginFilled',
    'general/menu',
    'general/optionsHorizontal',
    'general/optionsVertical',
    'general/plus',
    'general/reorder',
    'general/search',
    'general/shield',
    'general/showEye',
    'files/border',
    'files/borderError',
    'files/documentFilled',
    'files/documentOutline',
    'files/fileMultiple',
    'files/upload',
    'editor/bold',
    'editor/fonts',
    'editor/heading',
    'editor/italic',
    'editor/link',
    'editor/list',
    'editor/palette',
    'editor/redo',
    'editor/removeFormatting',
    'editor/space',
    'editor/strikethrough',
    'editor/typography',
    'editor/underline',
    'editor/undo',
    'communication/phone',
    'brandLogos/logoBlack',
    'brandLogos/logoBusiness',
    'brandLogos/logoGray',
    'brandLogos/logoInsurance',
    'brandLogos/logoMain',
    'brandLogos/logoWhite',
    'arrows/arrowCircle',
    'arrows/arrowDownRight',
    'arrows/arrowLink',
    'arrows/arrowRight',
    'arrows/arrowRotate',
    'arrows/arrowScroll'
  ]
} as const
