import type { Plugin } from 'vite'
import { generateDocs, Logger, removeMdx } from './utils'

export interface MDXOptions {
  /**
   * Путь до корневой директории storybook
   */
  storiesPath?: string | string[]
  /**
   * Указывает, включаем ли jsdoc в генерацию
   */
  jsdoc?: boolean
}

/**
 * Плагин для автоматической генерации документации
 * основанной на историях Storybook
 *
 * Рекурсивно обходит корневую директорию storybook
 * и генерирует рядом с каждым `.stories` файл `.docs.mdx` с документацией каждой истории
 * который будет сканироваться Storybook системой
 *
 * Как его использовать:
 *
 * @example
 * // Component.stories.ts
 * "use docs" // mark these stories to generate docs of each its stories
 *
 * import type { Meta, StoryObj } from "@storybook/react"
 * import { Button } from "@app/common"
 *
 * const meta = {
 *   title: "BASE/Button",
 *   component: Button,
 *   parameters: {
 *     layout: "centered",
 *   },
 *   // do not use 'autodocs' cuz it will be conflicted with this plugin
 *   tags: [
 *     ...anyTags
 *   ],
 *   args: {
 *     children: "Button",
 *   },
 * } satisfies Meta<typeof Button>
 *
 * export default meta
 *
 * type Story = StoryObj<typeof meta>
 *
 * // each story will export and generated by its content
 * /**
 * * also you can use js-doc for explain your story deeply
 * * if special characters are used in the js-doc, they must be escaped
 * *./
 * export const Default: Story = {
 *   args: {},
 * }
 *
 * @example
 * // it will generate this file
 * // Component.docs.mdx
 *
 * import { Meta, Canvas, Controls } from "@storybook/blocks"
 * import * as ButtonStories from "/path/to/story/Component.stories"
 *
 * # Button
 *
 * <Meta of={ButtonStories} />
 *
 * ## Button Default
 *
 * And js-doc will render on each story here
 *
 * <Canvas of={ButtonStories.Default} meta={ButtonStories} />
 * <Controls of={ButtonStories.Default} />
 *
 * @param options настройки генерации
 * @typeParam `storiesPath` - `string | string[]`
 * @typeParam `jsdoc` - `boolean`
 */
export const viteStorybookMdxGenerationPlugin = (options?: MDXOptions): Plugin => {
  const { storiesPath = ['src', 'stories'] } = options || {}

  const logger = new Logger('vite-storybook-mdx-generation-plugin')

  return {
    name: 'vite-storybook-mdx-generation-plugin',
    enforce: 'pre',
    configureServer: (server) => {
      logger.info('Generate MDX started.')
      removeMdx(storiesPath)
      generateDocs(storiesPath, options, logger)

      server.watcher.on('change', (path) => {
        if (path.match(/\.stories\.(ts|tsx)$/)) {
          logger.info('Story changed. Regenerate MDX.')
          removeMdx(storiesPath)
          generateDocs(storiesPath, options, logger)
        }
      })
    },
    transform: (code, id) => {
      if (id.match(/\.stories\.(ts|tsx)$/)) {
        return {
          code: code.replace(/^(?:[\s\n]*)(["']use docs["'];?)/m, ''),
          map: null
        }
      }
    },
    buildStart: () => {
      logger.info('Generate MDX for build.')
      removeMdx(storiesPath)
      generateDocs(storiesPath, options, logger)
    }
  }
}
