export * from './SocialLinks'
export * from './PhonesBlock'
export * from './NavLinks'
export * from '../../../shared/ui/Ligal'
export * from './Copyright'
export * from './FooterLogo'
export * from './SiteMap'
